### ISSUE TITLE
Bash prompt errors when mounting /hostroot 

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/ops-toolbelt#29]
**What happened**:

I am using the ops-toolbelt image with the host volume "/" mounted under "/hostroot".

When trying to change the root directory of my current shell process by executing `chroot /hostroot` - it works, but it seems the shell prompt is misconfigured.

```
$ chroot /hostroot
/bin/sh: 1: get_kube_ctx: not found
/bin/sh: 1: get_git_status: not found
\[\033]0;ip-10-250-8-164.eu-north-1.compute.internal\007\]\n\[\033[1m\]\[\]\u\[\033[0m\] at \[\033[1m\]\[\]ip-10-250-8-164.eu-north-1.compute.internal\[\033[0m\] in \[\033[1m\]\[\]\w\n\[\033[0m\]\[\033[1m\]$ \[\033[0m\]
```
 

subsequent commands:

```
$ docker ps
.....
80c-910a-0eabd6637adb_0
f82f0c731108        gcr.io/google_containers/pause-amd64:3.1                                           "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_node-exporter-qmqw9_kube-system_d0b0e8f7-68e3-4227-aab0-72b798439bdd_0
/bin/sh: 1: get_kube_ctx: not found
/bin/sh: 1: get_git_status: not found
```

**What you expected to happen**:
No errors when executing command when mounting the host root directory.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod that mounts the host root directory:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.privileged
  labels:
    app: root
#    networking.gardener.cloud/to-dns: allowed
  name: rootpod-test
#  namespace: kube-system
spec:
  containers:
    - command:
        - sleep
        - "10000000"
      image: eu.gcr.io/gardener-project/gardener/ops-toolbelt
      imagePullPolicy: Always
      name: root-container
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /hostroot
          name: root-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  #nodeName: ip-10-250-4-151.eu-north-1.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - hostPath:
        path: /
        type: ""
      name: root-volume
```

- exec into the pod
- execute `chroot /hostroot`

**Anything else we need to know**:

There are no errors when using the busybox image. That is e.g. what `gardenctl shell` uses. 

This is [where the promp is configured](https://github.com/gardener/ops-toolbelt/blob/43cdb45b8be10fc88efa9a00713dbb34baa1f6f2/dotfiles/.bash_prompt#L114)

**Environment**:
